#ifndef VANILLAENGINE_H
#define VANILLAENGINE_H

#include "Exception.h"
#include "Application.h"
#include "Entity.h"
#include "Component.h"

#include "Input.h"
#include "Resource.h"
#include "Resources.h"
#include "Renderer.h"
#include "ShaderProgram.h"
#include "VertexBuffer.h"
#include "VertexArray.h"
#include "Texture.h"
#include "Transform.h"
#include "Camera.h"
#include "Environment.h"
#include "Lights.h"
#include "PointLight.h"
#include "SpotLight.h"
#include "ShadowBox.h"
#include "ShadowManager.h"
#include "ShadowShader.h"
#include "RenderTexture.h"
#include "Skybox.h"
#include "Terrain.h"
#include "TerrainRenderer.h"
#endif